### Check Health
GET http://localhost:8080/api/v1/health

### Get Movie Information
GET http://localhost:8080/api/v1/create_movie

### Get Movie Information With id 1
GET http://localhost:8080/api/v1/show_movie/1